# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
TENSOR = torch.rand(7,7)
TENSOR

tensor([[0.0677, 0.9397, 0.6862, 0.1311, 0.1323, 0.2636, 0.9007],
        [0.1768, 0.6162, 0.5510, 0.5181, 0.6852, 0.8480, 0.8150],
        [0.2491, 0.3102, 0.7086, 0.9791, 0.9687, 0.4040, 0.1951],
        [0.0624, 0.2855, 0.1302, 0.2453, 0.2570, 0.4002, 0.4539],
        [0.9273, 0.9590, 0.7175, 0.4261, 0.5575, 0.9416, 0.0029],
        [0.5832, 0.6537, 0.2448, 0.6108, 0.5524, 0.3331, 0.8463],
        [0.7925, 0.8304, 0.3301, 0.2266, 0.3400, 0.6748, 0.8227]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
TENSOR_2 = torch.rand(1,7)
# Perform matrix multiplication 
print(TENSOR.matmul(TENSOR_2.T))
print(TENSOR.matmul(TENSOR_2.T).shape)

tensor([[0.9239],
        [1.1444],
        [0.9615],
        [0.4380],
        [1.3979],
        [0.6276],
        [0.9036]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [57]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
# Create two random tensors
TENSOR = torch.rand(7,7)
TENSOR_2 = torch.rand(1,7)
# Matrix multiply tensors
TENSOR_3 = TENSOR.matmul(TENSOR_2.T)
print(TENSOR_3,TENSOR_3.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [54]:
# Set random seed
RANDOM_SEED=1234
torch.manual_seed(seed=RANDOM_SEED)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:",device)
# Create two random tensors on GPU
TENSOR = torch.rand(2,3,device=device)
TENSOR_2 = torch.rand(2,3,device=device)
print(TENSOR)
print(TENSOR_2)


device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [56]:
# Perform matmul on tensor_A and tensor_B
TENSOR_3 = TENSOR.matmul(TENSOR_2.T)
print(TENSOR_3,TENSOR_3.shape)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [38]:
# Find max
print(f"Maximun:{TENSOR_3.max()}")
# Find min
print(f"Minimum:{TENSOR_3.min()}")

Maximun:0.7667766809463501
Minimum:0.27863210439682007


### 9. Find the maximum and minimum index values of the output of 7.

In [50]:
# Find arg max
max_index = torch.unravel_index(TENSOR_3.argmax(),TENSOR_3.shape)
max_index = (max_index[0].item(),max_index[1].item())
print(f"Max index:{max_index}")
# Find arg min
min_index = torch.unravel_index(TENSOR_3.argmin(),TENSOR_3.shape)
min_index = (min_index[0].item(),min_index[1].item())
print(f"Min index:{min_index}")

Max index:(0, 1)
Min index:(0, 0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [49]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)
# Create random tensor
TENSOR = torch.rand(1,1,1,10)

# Remove single dimensions
TENSOR_2 = torch.squeeze(TENSOR)

# Print out tensors and their shapes
print(TENSOR,TENSOR.shape)
print(TENSOR_2,TENSOR_2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
